apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-b-kueue-example

resources:
  - cluster-queue.yaml
  - hardware-profile.yaml
  - local-queue.yaml
  - team-namespace.yaml
