kind: Namespace
apiVersion: v1
metadata:
  name: team-b-kueue-example
  labels:
    opendatahub.io/dashboard: 'true'
    maas.opendatahub.io/gateway-access: 'true'
    kueue.openshift.io/managed: 'true'
