kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preemption-example-storage
  namespace: team-b-kueue-example
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
