apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications
type: Opaque
stringData:
  DB_CONNECTION_URL: "postgresql://maasadmin:workshop-maas@maas-postgresql.models-as-service-db.svc.cluster.local:5432/maasdb?sslmode=disable"
