apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: models-as-service-db

resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres.yaml
