apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  annotations:
    opendatahub.io/connections: llama-3-2-1b-instruct
    opendatahub.io/genai-use-case: chat
    opendatahub.io/hardware-profile-name: nvidia-gpu-serving
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/display-name: meta-llama/llama-3.2-1b-instruct
  name: llama-3-2-1b-instruct
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/genai-asset: 'true'
spec:
  model:
    name: "meta-llama/llama-3.2-1b-instruct"
    uri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-1b-instruct'
  replicas: 2
  router:
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
    route: {}
    scheduler:
      template:
        affinity:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: llama-3-2-1b-instruct
                  topologyKey: kubernetes.io/hostname
                weight: 100
        tolerations:
          - effect: NoSchedule
            key: nvidia.com/gpu
            operator: Exists
        containers:
          - name: main
  template:
    containers:
      - name: main
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '2'
            memory: 4Gi
            nvidia.com/gpu: '1'
